name:
    pynsm

channels:
    - pytorch
    - conda-forge

dependencies:
    - python=3.9
    - pip
    - pytest
    - numpy
    - scipy
    - tqdm
    - matplotlib
    - seaborn
    - pytorch
    - torchvision
    - scikit-learn
    - ipykernel
    - ipywidgets>=7.0,<8.0
    - jupyter
