name:
    pynsm

channels:
    - conda-forge
    - pytorch
    - nvidia

dependencies:
    - python=3.9
    - pytorch::pytorch-cuda=11.8
    - pytorch::pytorch=2.0
    - pytorch::torchvision=0.15
    - conda-forge::jupyter=1.0
    - conda-forge::ipykernel=6.23
    - conda-forge::ipywidgets=7.7
    - conda-forge::matplotlib=3.7
    - conda-forge::seaborn=0.12
    - conda-forge::scikit-learn=1.2
    - conda-forge::numpy=1.24
    - conda-forge::scipy=1.10
    - conda-forge::tqdm=4.65
    - conda-forge::pytest
    - conda-forge::pip=23
