site_name: pynsm
repo_url: https://github.com/Shagesh/pytorch-NSM

theme:
  name: 'material'
  palette:
    primary: 'light blue'
  features:
    - navigation.sections
    - content.code.copy
    - content.code.select
    
plugins:
    - search                            # make sure the search plugin is still enabled
    - mkdocstrings:                     # generating documentation from docstrings
        handlers:
          python:
            options:
              docstring_style: sphinx
    - gen-files:
        scripts:
            - docs/gen_ref_pages.py     # script for generating reference pages
    - literate-nav:
          nav_file: docs/SUMMARY.md     # navigation file for literate navigation
    - section-index                     # plugin for creating section index
    - mkdocs-jupyter
        
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
      
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Install pynsm:
      - Installation: install.md
    - Get started:
      - Basic usage: basic_usage.md
      - Examples:
        - Convolutional NSM: examples/demo_nsm_conv_mnist.ipynb
        - Supervised NSM: examples/demo_supervised_mnist.ipynb
    - Background:
      - Similarity matching: similarity.md
      - Supervised learning: supervised.md
    - How-to guides:
      - Build a classifier: classifier.md
      - Extend the library: extending.md
    - API reference: reference/
