site_name: pynsm
repo_url: https://github.com/Shagesh/pytorch-NSM

theme:
  name: 'material'
  palette:
    primary: 'light blue'
    features:
      - navigation.tabs
plugins:
    - search                            # make sure the search plugin is still enabled
    - mkdocstrings                      # generating documentation from docstrings
    - gen-files:
        scripts:
            - docs/gen_ref_pages.py     # script for generating reference pages
    - literate-nav:
          nav_file: docs/SUMMARY.md     # navigation file for literate navigation
    - section-index                     # plugin for creating section index
    - gallery:
        examples_dirs: docs/examples          # path to your example scripts
        gallery_dirs: docs/generated/gallery  # where to save generated gallery
nav:
    - Home: index.md
    - Tutorials: generated/gallery
    - Code References: reference/
