site_name: pynsm
repo_url: https://github.com/Shagesh/pytorch-NSM

theme:
  name: 'material'
  palette:
    primary: 'light blue'
  features:
    - navigation.sections
    
plugins:
    - search                            # make sure the search plugin is still enabled
    - mkdocstrings                      # generating documentation from docstrings
    - gen-files:
        scripts:
            - docs/gen_ref_pages.py     # script for generating reference pages
    - literate-nav:
          nav_file: docs/SUMMARY.md     # navigation file for literate navigation
    - section-index                     # plugin for creating section index
    - gallery:
        examples_dirs: docs/examples          # path to your example scripts
        gallery_dirs: docs/generated/gallery  # where to save generated gallery
        
markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
      
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - Home: index.md
    - Install pynsm:
      - Installation: install.md
    - Get started:
      - Basic usage: basic_usage.md
      - Examples: generated/gallery
    - Background:
      - Similarity matching: similarity.md
      - Supervised learning: supervised.md
    - How-to guides:
      - Build a classifier: classifier.md
      - Extend the library: extending.md
    - API reference: reference/
